version = 1
SPDX-PackageName = "vgopath"
SPDX-PackageSupplier = "IronCore authors <ospo@sap.com>"
SPDX-PackageDownloadLocation = "https://github.com/ironcore-dev/vgopath"

[[annotations]]
path = [
    ".github/**",
    ".gitignore",
    ".golangci.yaml",
    "CODEOWNERS",
    "CODE_OF_CONDUCT.md",
    "Makefile",
    "go.mod",
    "go.sum",
    "internal/testdata/gocat/go.mod",
    "internal/testdata/modules.json.stream",
    "REUSE.toml"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "README.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 SAP SE or an SAP affiliate company and IronCore contributors"
SPDX-License-Identifier = "Apache-2.0"
